// const music = require('music.json')nod
// const technology = 'assets/technology.json'
// const sports =  'assets/sports.json'

const express = require('express');

var router = express.Router();


router.get('/', (req, res) => {
  res.send('hello world')
})

router.post('/api', (req, res) => {
  // console.log(req, 'request')
  // console.log(req.body)
  let selection = req.body.category
  console.log(selection)
  switch (Number(selection)) {
    case 0:
      //Case for Music
      console.log(`Music`)
      res.json({ "response_code": 0, "results": [{ "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "Who recorded the 1975 album &#039;Captain Fantastic and the Brown Dirt Cowboy&#039;?", "correct_answer": "Elton John", "incorrect_answers": ["John Denver", "Billy Joel", "Joe Cocker"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "Which M83 album is the song &quot;Midnight City&quot; featured in?", "correct_answer": "Hurry Up, We&#039;re Dreaming", "incorrect_answers": ["Saturdays = Youth", "Before the Dawn Heals Us", "Junk"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "How many members are there in the idol group &quot;&micro;&#039;s&quot;?", "correct_answer": "9", "incorrect_answers": ["48", "6", "3"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "Which of these songs is not by Tatsuro Yamashita?", "correct_answer": "Lucky Lady Feel So Good ", "incorrect_answers": ["Merry-Go Round", "Let&#039;s Dance Baby", "Love Talkin&#039;"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "The key of sharps does the key of G# minor contain?", "correct_answer": "5", "incorrect_answers": ["3", "7", "0"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "In the Panic! At the Disco&#039;s song &quot;Nothern Downpour&quot;, which lyric follows &#039;I know the world&#039;s a broken bone&#039;.", "correct_answer": "&quot;So melt your headaches call it home&quot;", "incorrect_answers": ["&quot;So sing your song until you&#039;re home&quot;", "&quot;So let them know they&#039;re on their own&quot;", "&quot;So start a fire in their cold stone&quot;"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "Which company did the animation for Peter Gabriel&#039;s Video Sledgehammer (1986)?", "correct_answer": "Aardman Animations", "incorrect_answers": ["HIT Entertainment", "Illumination Entertainment", "VIZ Media"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "Which of Michael Jackson&#039;s albums sold the most copies?", "correct_answer": "Thriller", "incorrect_answers": ["Dangerous", "Bad", "Off the Wall"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "What year was Min Yoongi from South Korea boy band &quot;BTS&quot; born in?", "correct_answer": "1993", "incorrect_answers": ["1992", "1995", "1994"] }, { "category": "Entertainment: Music", "type": "multiple", "difficulty": "hard", "question": "What was the name of the cold-war singer who has a song in Grand Theft Auto IV, and a wall landmark in Moscow for his memorial?", "correct_answer": "Viktor Tsoi", "incorrect_answers": ["Jimi Hendrix", "Brian Jones", "Vladimir Vysotsky"] }] })
      break;
    case 1:
      //Case for Technology
      console.log(`Technology`)
      res.json({ "response_code": 0, "results": [{ "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "How many Hz does the video standard PAL support?", "correct_answer": "50", "incorrect_answers": ["59", "60", "25"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "The internet domain .fm is the country-code top-level domain for which Pacific Ocean island nation?", "correct_answer": "Micronesia", "incorrect_answers": ["Fiji", "Tuvalu", "Marshall Islands"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?", "correct_answer": "Heartbleed", "incorrect_answers": ["Shellshock", "Corrupted Blood", "Shellscript"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "Which data structure does FILO apply to?", "correct_answer": "Stack", "incorrect_answers": ["Queue", "Heap", "Tree"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "What is the name of the process that sends one quibit of information using two bits of classical information?", "correct_answer": "Quantum Teleportation", "incorrect_answers": ["Super Dense Coding", "Quantum Entanglement", "Quantum Programming"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "What internet protocol was documented in RFC 1459?", "correct_answer": "IRC", "incorrect_answers": ["HTTP", "HTTPS", "FTP"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "What does the International System of Quantities refer 1024 bytes as?", "correct_answer": "Kibibyte", "incorrect_answers": ["Kylobyte", "Kilobyte", "Kelobyte"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "Which RAID array type is associated with data mirroring?", "correct_answer": "RAID 1", "incorrect_answers": ["RAID 0", "RAID 10", "RAID 5"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "What was the first company to use the term &quot;Golden Master&quot;?", "correct_answer": "Apple", "incorrect_answers": ["IBM", "Microsoft", "Google"] }, { "category": "Science: Computers", "type": "multiple", "difficulty": "hard", "question": "Who invented the &quot;Spanning Tree Protocol&quot;?", "correct_answer": "Radia Perlman", "incorrect_answers": ["Paul Vixie", "Vint Cerf", "Michael Roberts"] }] })
      break;
    case 2:
      //Case for Sports
      console.log(`Sports`)
      res.json({ "response_code": 0, "results": [{ "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "How many times did Martina Navratilova win the Wimbledon Singles Championship?", "correct_answer": "Nine", "incorrect_answers": ["Ten", "Seven", "Eight"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "What tool lends it&#039;s name to a last-stone advantage in an end in Curling?", "correct_answer": "Hammer", "incorrect_answers": ["Wrench", "Drill", "Screwdriver"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "With which doubles partner did John McEnroe have most success?", "correct_answer": "Peter Fleming", "incorrect_answers": ["Mark Woodforde", "Michael Stich", "Mary Carillo"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "Which car company is the only Japanese company which won the 24 Hours of Le Mans?", "correct_answer": "Mazda", "incorrect_answers": ["Toyota", "Subaru", "Nissan"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "Which Italian footballer told Neuer where he&#039;s putting his shot and dragging it wide, during the match Italy-Germany, UEFA EURO 2016?", "correct_answer": "Pelle", "incorrect_answers": ["Insigne", "Barzagli", "Giaccherini"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "Which male player won the gold medal of table tennis singles in 2016 Olympics Games?", "correct_answer": "Ma Long (China)", "incorrect_answers": ["Zhang Jike (China)", "Jun Mizutani (Japan)", "Vladimir Samsonov (Belarus)"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "Which female player won the gold medal of table tennis singles in 2016 Olympics Games?", "correct_answer": "DING Ning (China)", "incorrect_answers": ["LI Xiaoxia (China)", "Ai FUKUHARA (Japan)", "Song KIM (North Korea)"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "What is the full name of the footballer &quot;Cristiano Ronaldo&quot;?", "correct_answer": "Cristiano Ronaldo dos Santos Aveiro", "incorrect_answers": ["Cristiano Ronaldo los Santos Diego", "Cristiano Armando Diego Ronaldo", "Cristiano Luis Armando Ronaldo"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "Which year was the third Super Bowl held?", "correct_answer": "1969", "incorrect_answers": ["1968", "1971", "1970"] }, { "category": "Sports", "type": "multiple", "difficulty": "hard", "question": "What team did England beat in the semi-final stage to win in the 1966 World Cup final?", "correct_answer": "Portugal", "incorrect_answers": ["West Germany", "Soviet Union", "Brazil"] }] })
      break;
    default:
      console.log('invalid choice')
  }


})



module.exports = router;
